### PR TITLE
feat:adding CyberneticsSpectacleGlasses codes

### PR DESCRIPTION
**Pull request by kazutan1230**
### What does this PR do?

I added CyberneticsSpectacleGlasses codes which can control LED lights and change how to light by pushing button, and play a song.

### How did you verify your code works?

I have run the codes on my Ichigojam.

### CODE REVIEW

**Review by Marukome0743 — APPROVED** [review]
GochiusaRizeGIF

**Comment by kazutan1230** [comment]
I can't sign the commit [9b69c95](https://github.com/OpenUp-LabTakizawa/IchigoJam/pull/62/commits/9b69c956f8ce228a475d67897573201741223b82) because I added files at the codespaces.
Please forgive me.

**Review by HaradaTakayuki — APPROVED** [review]
確認致しました。

**Comment by kazutan1230** [comment]
> I can't sign the commit [9b69c95](https://github.com/OpenUp-LabTakizawa/IchigoJam/pull/62/commits/9b69c956f8ce228a475d67897573201741223b82) because I added files at the codespaces. Please forgive me.

I've found how to change commits pushed to github repositories,
then have could verify.

**Pull request merged**
